Repository lhj0621/nodeswork_boards_server, pull requests merged in 2021-11, with the labels that each got.

#18 chore/데이터베이스 세팅 및 app.ts 생성
  package-lock.json
  src/core/app.ts
  src/core/database.ts
  src/index.ts
  src/model/answers.model.ts
  src/model/boards.model.ts
  src/model/comments.model.ts
  src/model/users.model.ts
Labels: chore

#19 Feature/signup
  package-lock.json
  package.json
  src/routes/index.ts
  src/routes/users.routers.ts
  src/users/users.controller.ts
  src/users/users.service.ts
  src/utils/createError.ts
Labels: feat

#24 refactor: member_id -> user_id로 수정
  src/model/answers.model.ts
  src/model/boards.model.ts
  src/model/comments.model.ts
Labels: refactor
